# This is the map of the whole thing

site_name: 8-line Olfactometer - all of it
site_url: https://test-olfacontrol.readthedocs.io
#site_description: Open source, Python based, behavioural experiment control.
site_author: Shannon Toole
theme:
    name: readthedocs

repo_url: https://github.com/tooles01/test_OlfaControl

plugins:
    - search:

nav:
- Home: index.md
- 8-line Olfactometer:
    - Overview: 8-line Olfactometer/readme.md
    - Hardware: 8-line Olfactometer/readme.md
    - Electronics: 8-line Olfactometer/Electronics/README.md
    #- Synchronisation: user-guide/synchronisation.md 
    #- pyControl data: user-guide/pycontrol-data.md
    #- Troubleshooting: user-guide/troubleshooting.md
- 8-line Mixing Chamber:
    - Electronics: 8-line Mixing Chamber/Electronics/README.md
    - Hardware: 8-line Mixing Chamber/For Manufacturing (Hardware)/README.md

#- About:
#    - Release notes: about/release-notes.md
#    - License: about/license.md

#- Quick Links:
#    - Help and discussions: https://github.com/orgs/pyControl/discussions
#    - GitHub repositories: https://github.com/pycontrol
#    - Manuscript:  https://elifesciences.org/articles/67846
#    - pyPhotometry: https://pyphotometry.readthedocs.io/

#copyright: Copyright &copy; 2016 - 2024 Thomas Akam

# Uncomment to generate PDF version of docs using mkdocs-with-pdf
# plugins: 
#    - with-pdf:
#        cover_title: pyControl
#        cover_subtitle: Open source, Python based, behavioural experiment control.
#        output_path: C:\Users\thoma\Downloads\pyControl_docs.pdf