site_name: pyControl
#site_url: https://pycontrol.readthedocs.io/
#site_description: Open source, Python based, behavioural experiment control.
#site_author: Thomas Akam
theme:
    name: readthedocs
    #logo: logo.png

#markdown_extensions:
#    - admonition
#    - toc:
#        permalink: True

#repo_url: https://github.com/pycontrol/pycontrol-docs

plugins:
    - search:
    #- search:
    #    separator: '[\s\-\_\.]+'

nav:
- Home: index.md
- 8-line Olfactometer:
    - Electronics: 8-line Olfactometer/Electronics/README.md
    - Hardware: 8-line Olfactometer/readme.md
    #- Hardware: user-guide/hardware.md
    #- Synchronisation: user-guide/synchronisation.md 
    #- pyControl data: user-guide/pycontrol-data.md
    #- Troubleshooting: user-guide/troubleshooting.md
#- Contributing: contributing.md
- 8-line Mixing Chamber:
    - Electronics: 8-line Mixing Chamber/Electronics/README.md
    - Hardware: 8-line Mixing Chamber/For Manufacturing (Hardware)/README.md

#- About:
#    - Release notes: about/release-notes.md
#    - License: about/license.md

#- Quick Links:
#    - Help and discussions: https://github.com/orgs/pyControl/discussions
#    - GitHub repositories: https://github.com/pycontrol
#    - Manuscript:  https://elifesciences.org/articles/67846
#    - pyPhotometry: https://pyphotometry.readthedocs.io/

#copyright: Copyright &copy; 2016 - 2024 Thomas Akam

# Uncomment to generate PDF version of docs using mkdocs-with-pdf
# plugins: 
#    - with-pdf:
#        cover_title: pyControl
#        cover_subtitle: Open source, Python based, behavioural experiment control.
#        output_path: C:\Users\thoma\Downloads\pyControl_docs.pdf